package com.bangkit.iproductapp.model

object FakeProductDataSource {
    val dummyProduct = listOf(
        Product(
            id = 1,
            title = "iPhone 9",
            description = "An apple mobile which is nothing like apple",
            price = 549,
            brand = "Apple",
            category = "smartphones",
            rating = 4.69,
            thumbnail = "https://i.dummyjson.com/data/products/1/thumbnail.jpg",
        ),
        Product(
            id = 2,
            title = "iPhone X",
            description = "SIM-Free, Model A19211 6.5-inch Super Retina HD display with OLED technology A12 Bionic chip with ...",
            price = 899,
            brand = "Apple",
            category = "smartphones",
            rating = 3.44,
            thumbnail = "https://i.dummyjson.com/data/products/2/thumbnail.jpg",
        ),
        Product(
            id = 3,
            title = "Samsung Universe 9",
            description = "Samsung's new variant which goes beyond Galaxy to the Universe",
            price = 1249,
            brand = "Samsung",
            category = "smartphones",
            rating = 4.09,
            thumbnail = "https://i.dummyjson.com/data/products/3/thumbnail.jpg",
        ),
        Product(
            id = 4,
            title = "OPPO F19",
            description = "OPPO F19 is officially announced on April 2021.",
            price = 280,
            brand = "OPPO",
            category = "smartphones",
            rating = 4.3,
            thumbnail = "https://i.dummyjson.com/data/products/4/thumbnail.jpg",
        ),
        Product(
            id = 5,
            title = "Huawei P30",
            description = "Huawei’s re-badged P30 Pro New Edition was officially unveiled yesterday in Germany and now the device has made its way to the UK.",
            price = 499,
            brand = "Huawei",
            category = "smartphones",
            rating = 4.09,
            thumbnail = "https://i.dummyjson.com/data/products/5/thumbnail.jpg",
        ),
        Product(
            id = 6,
            title = "MacBook Pro",
            description = "MacBook Pro 2021 with mini-LED display may launch between September, November",
            price = 1749,
            brand = "Apple",
            category = "laptops",
            rating = 4.57,
            thumbnail = "https://i.dummyjson.com/data/products/6/thumbnail.png",
        ),
        Product(
            id = 7,
            title = "Samsung Galaxy Book",
            description = "Samsung Galaxy Book S (2020) Laptop With Intel Lakefield Chip, 8GB of RAM Launched",
            price = 1499,
            brand = "Samsung",
            category = "laptops",
            rating = 4.25,
            thumbnail = "https://i.dummyjson.com/data/products/7/thumbnail.jpg",
        ),
        Product(
            id = 8,
            title = "Microsoft Surface Laptop 4",
            description = "Style and speed. Stand out on HD video calls backed by Studio Mics. Capture ideas on the vibrant touchscreen.",
            price = 1499,
            brand = "Microsoft Surface",
            category = "laptops",
            rating = 4.43,
            thumbnail = "https://i.dummyjson.com/data/products/8/thumbnail.jpg",
        ),
        Product(
            id = 9,
            title = "Infinix INBOOK",
            description = "Infinix Inbook X1 Ci3 10th 8GB 256GB 14 Win10 Grey – 1 Year Warranty",
            price = 1099,
            brand = "Infinix",
            category = "laptops",
            rating = 4.54,
            thumbnail = "https://i.dummyjson.com/data/products/9/thumbnail.jpg",
        ),
        Product(
            id = 10,
            title = "HP Pavilion 15-DK1056WM",
            description = "HP Pavilion 15-DK1056WM Gaming Laptop 10th Gen Core i5, 8GB, 256GB SSD, GTX 1650 4GB, Windows 10",
            price = 1099,
            brand = "HP Pavilion",
            category = "laptops",
            rating = 4.43,
            thumbnail = "https://i.dummyjson.com/data/products/10/thumbnail.jpeg",
        ),
    )
}
